server:
  port: 9002
spring:
  application:
    name: tensquare-base #给当前项目起个名称
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/tensquare_base2?characterEncoding=utf-8
    username: root
    password: root
  rabbitmq:
    host: 127.0.0.1
  cloud:
    refresh:
      refreshable: none
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/


